info/news/__init__.py
from flask import Blueprint

news_blue = Blueprint('news', __name__, url_prefix='/news')

from . import views

info/news/views.py
from flask import abort, jsonify
from flask import current_app
from flask import g
from flask import render_template
from flask import request
from flask import session

from info import db
from info.models import User, News, Comment, CommentLike
from info.utils.common import user_login_data
from info.utils.response_code import RET
from . import news_blue



@news_blue.route('/followed_user', methods=["POST", "GET"])
@user_login_data
def followed_user():
    # 已经登陆的用户
    login_user = g.user
    if not login_user:
        return jsonify(errno=RET.SESSIONERR, errmsg='用户未登录')
    user_id = request.json.get('user_id')

    # 作者用户
    author_user = User.query.filter(User.id == user_id).first()
    action = request.json.get('action')

    if not all([user_id, action]):
        return jsonify(errno=RET.PARAMERR, errmsg='参数不全')
    if action not in ('follow','unfollow'):
        return jsonify(errno=RET.PARAMERR,errmsg='参数不对')

    if action == 'follow':
        if author_user.followers.filter(User.id ==login_user.id).count()>0:
            return jsonify(errno=RET.DATAEXIST,errmsg='当前已经关注')
        author_user.followers.append(login_user)
    else:
        if author_user.followers.filter(User.id ==login_user.id).count()>0:
            author_user.followers.remove(login_user)

    db.session.commit()
    return jsonify(errno=RET.OK,errmsg='操作成功')


@news_blue.route('/<int:news_id>')
@user_login_data
def news_detail(news_id):
    user = g.user
    # 获取当前新闻的所有评论
    '''
    通过新闻id就可以查到新闻评论列表.
    '''
    comments = Comment.query.filter(Comment.news_id == news_id).order_by(Comment.create_time.desc()).all()
    comments_list = []
    '''
    获取到新闻详情页面评论点赞的数据
    '''
    commentLike_list = []
    comment_like_ids = []
    if user:
        commentLike_list = CommentLike.query.filter(CommentLike.user_id == user.id).all()
        comment_like_ids = [comment_like.comment_id for comment_like in commentLike_list]

    for comment in comments:
        comment_dict = comment.to_dict()
        comment_dict['is_like'] = False
        # comment_like_ids:所有的评论点赞id
        if comment.id in comment_like_ids:
            comment_dict['is_like'] = True
        comments_list.append(comment_dict)

    '''
    首页右边的热门新闻排行
    '''
    news_rank = News.query.order_by(News.clicks.desc()).limit(10)
    news_rank_list = []
    for news in news_rank:
        news_rank_list.append(news.to_dict())

    '''
    获取新闻的详细数据
    '''
    news = News.query.get(news_id)

    # 判断是否收藏该新闻,默认值为false
    is_collected = False

    # 判断登录的用户是否关注当前新闻作者
    is_followed = False

    # 判断用户是否收藏过该新闻
    if user and news.user:
        if news in g.user.collection_news:
            is_collected = True
        if news.user.followers.filter(User.id == user.id).count() > 0:
            is_followed = True

    data = {
        'news': news.to_dict(),
        'click_news_list': news_rank_list,
        'user_info': user.to_dict() if user else None,
        'is_collected': is_collected,
        'is_followed': is_followed,
        'comments': comments_list
    }

    # 在详情页面继承父类的模板的时候需要将data也传过去,  否则会报错.
    return render_template('news/detail.html', data=data)


# 运行测试，g 变量是一个应用上下文变量，类似于一个全局变量，
# 但是 g 变量里面的保存的值是相对于每次请求的，不同的请求，g 变量里面
# 保存的值是不同的，所以同一次请求，可以使用 g 变量来保存值用于进行函数的传递。


@news_blue.route('/news_collect', methods=["POST"])
@user_login_data
def news_collect():
    news_id = request.json.get('news_id')
    # 前端用户传过来的动作,收藏新闻或者取消收藏新闻.
    action = request.json.get('action')
    user = g.user
    news = News.query.get(news_id)
    if not user:
        return jsonify(errno=RET.SESSIONERR, errmsg='用户未登录')

    if action == 'collect':
        user.collection_news.append(news)
    else:
        user.collection_news.remove(news)

    db.session.commit()
    return jsonify(errno=RET.OK, errmsg='收藏成功')


@news_blue.route('/news_comment', methods=['POST', 'GET'])
@user_login_data
def news_comment():
    user = g.user
    if not user:
        return jsonify(errno=RET.SESSIONERR, errmsg='用户未登陆')
    news_id = request.json.get('news_id')
    comment_str = request.json.get('comment')
    parent_id = request.json.get('parent_id')
    if not all([news_id, comment_str]):
        return jsonify(errno=RET.PARAMERR, errmsg='参数不足')
    '''
    用户登陆才能评论
    评论前需要知道新闻id,-----
    评论之后,只要把评论信息存到数据库,为了方便下次用户可以看到评论
    '''
    news = News.query.get(news_id)
    comment = Comment()
    comment.user_id = user.id
    comment.news_id = news.id
    comment.content = comment_str
    if parent_id:
        comment.parent_id = parent_id
    db.session.add(comment)
    db.session.commit()
    return jsonify(errno=RET.OK, errmsg='评论成功', data=comment.to_dict())


@news_blue.route('/comment_like', methods=['POST'])
@user_login_data
def comment_like():
    user = g.user
    '''
    1.点赞必须用户登录
    2.点赞是针对当前评论,有评论才需要点赞,首先查询评论点赞
    3.查询评论,在查询点赞评论的时候,需要根据当前的评论id,
    和用户id进行查询
    4.查询出来点赞的评论之后,需要进行判断,当前这条评论是否有值
    如果没有值才可以进行点赞
    '''
    if not user:
        return jsonify(errno=RET.SESSIONERR, errmsg='请登录')
    comment_id = request.json.get('comment_id')
    news_id = request.json.get('news_id')
    action = request.json.get('action')

    comment = Comment.query.get(comment_id)
    if not all([comment_id, news_id, action]):
        return jsonify(errno=RET.PARAMERR, errmsg='参数不全')
    if not comment_id:
        return jsonify(errno=RET.PARAMERR, errmsg='没有评论')

    comment_like = CommentLike().query.filter(CommentLike.comment_id == comment_id,
                                              CommentLike.user_id == user.id).first()

    if action == 'add':
        # comment_like = CommentLike().query.filter(CommentLike.comment_id == comment_id,CommentLike.user_id == user.id).first()
        if not comment_like:
            comment_like = CommentLike()
            comment_like.comment_id = comment_id
            comment_like.user_id = user.id
            db.session.add(comment_like)
            comment.like_count += 1

    else:
        # comment_like = CommentLike().query.filter(CommentLike.comment_id == comment_id,CommentLike.user_id == user.id).first()
        if comment_like:
            db.session.delete(comment_like)
            comment.like_count -= 1

    db.session.commit()
    return jsonify(errno=RET.OK, errmsg='操作成功.')

info/user/__init__.py
from flask import Blueprint

profile_blue = Blueprint('user',__name__,url_prefix='/user')

from . import views

info/user/views.py
from flask import g, jsonify
from flask import redirect
from flask import render_template
from flask import request

from info import constants
from info import db
from info.models import News, Category, User
from info.utils.image_storage import storage
from info.utils.response_code import RET
from . import profile_blue
from info.utils.common import user_login_data


@profile_blue.route('/other_news_list')
def other_news_list():
    page = request.args.get('p', 1)
    other_id = request.args.get('user_id')
    try:
        page = int(page)
    except Exception as e:
        page = 1
    print(other_id)
    paginate = News.query.filter(News.user_id == other_id).order_by(News.create_time.desc()).paginate(page, 10, False)
    news_items = paginate.items
    current_page = paginate.page
    total_page = paginate.pages
    news_list = []
    for item in news_items:
        news_list.append(item.to_review_dict())
    data = {
        'news_list': news_list,
        'current_page': current_page,
        'total_page': total_page
    }

    return jsonify(errno=RET.OK, errmsg='ok', data=data)


@profile_blue.route('/other_info')
@user_login_data
def other_info():
    user = g.user
    # if not user:
    #     return jsonify(errno=RET.SESSIONERR,errmsg='用户未登录')
    user_id = request.args.get('id')
    try:
        other = User.query.get(user_id)
    except Exception as e:
        print(e)

    is_followed = False
    if user:
        if other.followers.filter(User.id == user.id).count() > 0:
            is_followed = True

    data = {
        'user_info': user.to_dict(),
        'other_info': other.to_dict(),
        'is_followed': is_followed
    }
    return render_template('news/other.html', data=data)


@profile_blue.route('/user_follow')
@user_login_data
def user_follow():
    user = g.user
    page = request.args.get('p', 1)
    try:
        page = int(page)
    except Exception as e:
        page = 1

    paginate = user.followed.paginate(page, 10, False)
    followed_users = paginate.items
    current_page = paginate.page
    total_page = paginate.pages

    followed_list = []
    for follower in followed_users:
        followed_list.append(follower.to_dict())

    data = {
        'current_page': current_page,
        'total_page': total_page,
        'users': followed_list
    }

    return render_template('news/user_follow.html', data=data)
    pass


@profile_blue.route('/news_list')
@user_login_data
def news_list():
    user = g.user
    page = request.args.get("p", 1)
    print(page)
    try:
        page = int(page)
    except Exception as e:
        page = 1

    print(user.id)
    paginate = News.query.filter(News.user_id == user.id).paginate(page, 2, False)
    items = paginate.items
    current_page = paginate.page
    total_page = paginate.pages

    items_list = []
    for item in items:
        items_list.append(item.to_review_dict())

    data = {
        "news_list": items_list,
        "current_page": current_page,
        "total_page": total_page
    }
    return render_template("news/user_news_list.html", data=data)


@profile_blue.route('/news_release', methods=['POST', 'GET'])
@user_login_data
def news_release():
    user = g.user

    if request.method == "GET":
        categories = Category.query.filter(Category.id != 1).all()
        categories_list = []
        for cate in categories:
            categories_list.append(cate.to_dict())

        data = {
            # 'user_info': user.to_dict if user else None,
            'categories': categories
        }
        return render_template('news/user_news_release.html', data=data)

    title = request.form.get('title')
    category_id = request.form.get('category_id')
    print(category_id)
    digest = request.form.get('digest')
    index_image = request.files.get('index_image').read()
    content = request.form.get('content')
    source = '个人发布'
    print(title, category_id)
    print(digest)
    print(index_image)
    print(content)
    if not all([title, source, digest, content, index_image, category_id]):
        return jsonify(errno=RET.PARAMERR, errmsg='参数不全')

    news = News()
    key = storage(index_image)
    index_image_url = constants.QINIU_DOMIN_PREFIX + key
    news.title = title
    news.category_id = category_id
    news.content = content
    news.digest = digest
    news.index_image_url = index_image_url
    news.status = 1
    news.source = source
    news.user_id = user.id  # user.id   不写不报错.  但是会过滤不出来.
    db.session.add(news)
    db.session.commit()

    return jsonify(errno=RET.OK, errmsg='ok')


@profile_blue.route('/collection', methods=['POST', 'GET'])
@user_login_data
def user_collection():
    user = g.user
    if not user:
        return redirect('/')
    # if request.method == 'GET':
    #     return render_template('news/user_collection.html', data={'user_info': user.to_dict() if user else None})
    page = request.args.get('p', 1)
    try:
        page = int(page)
    except Exception as e:
        page = 1

    # 分页显示的方法 paginate(页码,条目数,是否显示错误路劲)
    paginate = user.collection_news.order_by(News.create_time.desc()).paginate(page, 10, False)
    items = paginate.items  # 总条目数量
    current_page = paginate.page  # 当前页面 从第几页开始
    total_page = paginate.pages  # 总页数

    collections = []
    for collection_news in items:
        collections.append(collection_news)
    data = {
        'collections': collections,
        'current_page': current_page,
        'total_page': total_page,
    }
    return render_template('news/user_collection.html', data=data)


@profile_blue.route('/pass_info', methods=['GET', 'POST'])
@user_login_data
def pass_info():
    user = g.user
    if not user:
        return redirect('/')
    if request.method == 'GET':
        data = {
            "user_info": user.to_dict() if user else None
        }
        return render_template('news/user_pass_info.html', data=data)

    old_password = request.json.get('old_password')
    new_password = request.json.get('new_password')
    print(old_password)
    print(new_password)

    if not all([old_password, new_password]):
        return jsonify(errno=RET.PARAMERR, errmsg='参数不全')
    if not user.check_password(old_password):
        return jsonify(errno=RET.PWDERR, errmsg='原密码错误.')

    user.password = new_password
    db.session.commit()
    return jsonify(errno=RET.OK, errmsg='修改成功')


@profile_blue.route('/pic_info', methods=['GET', 'POST'])
@user_login_data
def pic_info():
    user = g.user
    if not user:
        return redirect('/')
    if request.method == 'GET':
        return render_template('news/user_pic_info.html', data={'user_info': user.to_dict()})
    avatar = request.files.get('avatar').read()
    if not avatar:
        return jsonify(errno=RET.PARAMERR, errmsg='参数不全')

    # 再将文件上传到七牛云
    key = storage(avatar)
    user.avatar_url = key
    db.session.commit()
    return jsonify(errno=RET.OK, errmsg='操作成功', data=constants.QINIU_DOMIN_PREFIX + key)


@profile_blue.route('/base_info', methods=['GET', 'POST'])
@user_login_data
def base_info():
    user = g.user
    if not user:
        return redirect('/')
    if request.method == 'GET':
        return render_template('news/user_base_info.html', data={'user_info': user.to_dict()})
    nick_name = request.json.get('nick_name')
    signature = request.json.get('signature')
    gender = request.json.get('gender')

    if not all([nick_name, signature, gender]):
        return jsonify(errno=RET.PARAMERR, errmsg='参数不全')

    user.nick_name = nick_name
    user.signature = signature
    user.gender = gender
    db.session.commit()
    return jsonify(errno=RET.OK, errmsg='操作成功')


    # return render_template('news/user_base_info.html')


@profile_blue.route('/info')
@user_login_data
def get_user_info():
    user = g.user
    if not user:
        return redirect('/')
    # if request.method == 'GET':  # GET请求是请求数据,   post是提交数据
    data = {
        'user_info': user.to_dict() if user else None
    }
    return render_template('news/user.html', data=data)

info/templates/news/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block titleBlock %}{% endblock %}</title>
{% block link_scriptBlock %}
    <link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">
    <link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">
    <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>

    <script type="text/javascript" src="../../static/news/js/main.js"></script>
{% endblock %}

    {% block scriptBlock %}{% endblock %}
</head>
<body>
<div class="header_con">
    <div class="header">
        <a href="/" class="logo fl"><img src="../../static/news/images/logo.png" alt="logo"></a>
        {% block categoryBlock %}

        {% endblock %}

        {# 判断用户是否登录 #}
        {% if data.user_info %}
            {# 如果登录，则显示用户信息 #}
            <div class="user_login fr">
                <img src="




                        {% if data.user_info.avatar_url %}{{ data.user_info.avatar_url }}{% else %}../../static/news/images/person01.png{% endif %}"
                     class="lgin_pic">
                <a href="/user/info" id="nick_name">{{ data.user_info.nick_name }}</a>
                <a href="javascript:;" onclick="logout()">退出</a>
            </div>
        {% else %}
            {# 如果没有登录，则显示登录注册按钮 #}
            <div class="user_btns fr">
                <a href="javascript:;" class="login_btn">登录</a> / <a href="javascript:;" class="register_btn">注册</a>
            </div>
        {% endif %}


    </div>
</div>

<div class="conter_con">
    {% block contentBlock %}

    {% endblock %}

{% block rankBlock %}
    <div class="rank_con fr">
        {% block authorBlock %}

        {% endblock %}
        <div class="rank_title">
            <h3>点击排行</h3>
        </div>
        <ul class="rank_list">
            {% for news in data.click_news_list %}
                <li><span class="{{ loop.index0 | indexClass }}">{{ loop.index }}</span><a href="#">{{ news.title }}</a>
                </li>
            {% endfor %}

        </ul>
    </div>
{% endblock %}
</div>
{% block footerBlock %}
<div class="footer">
    <div class="footer_links">
        <a href="">关于我们</a>
        <span>|</span>
        <a href="">联系我们</a>
        <span>|</span>
        <a href="">招聘人才</a>
        <span>|</span>
        <a href="">友情链接</a>
    </div>
    <p class="copyright">
        CopyRight © 2018 新经资讯信息技术有限公司 All Rights Reserved<br/>
        电话：010-****888 京ICP备*******8号
    </p>
</div>
{% endblock %}
<!-- 登录表单 -->
<form class="login_form_con">
    <div class="login_form">
        <div class="login_title">
            <h3>登 录</h3>
            <a href="javascript:;" class="shutoff"></a>
        </div>
        <div class="form_group">
            <input id="mobile" type="text" name="mobile" autocomplete="off">
            <div class="input_tip">手机号</div>
            <div id="login-mobile-err" class="error_tip">手机号不能为空</div>
        </div>
        <div class="form_group">
            <input id="password" type="password" name="password">
            <div class="input_tip">密码(不少于6位)</div>
            <div id="login-password-err" class="error_tip">密码不能为空</div>
        </div>
        <input type="submit" name="" value="登 录" class="input_sub">
        <div class="down_link">还没有账号？<a href="javascript:;" class="to_register">立即注册</a></div>
    </div>
    <div class="mask"></div>
</form>

<!-- 注册表单 -->
<form class="register_form_con">
    <div class="register_form">
        <div class="register_title">
            <h3>注 册</h3>
            <a href="javascript:;" class="shutoff"></a>
        </div>
        <div class="form_group">
            <input type="text" name="mobile" autocomplete="off" id="register_mobile" class="phone_input">
            <div class="input_tip">手机号</div>
            <div id="register-mobile-err" class="error_tip">手机号不能为空</div>
        </div>
        <div class="form_group">
            <input type="text" name="code_pwd" id="imagecode" class="code_pwd">
            <div class="input_tip">图形验证码</div>
            <img src="../../static/news/images/pic_code.png" class="get_pic_code" onclick="generateImageCode()">
            <div id="register-image-code-err" class="error_tip">图形码不能为空</div>
        </div>
        <div class="form_group">
            <input type="text" name="smscode" id="smscode" class="code_pwd">
            <div class="input_tip">手机验证码</div>
            <a href="javascript:;" class="get_code" onclick="sendSMSCode()">点击获取验证码</a>
            <div id="register-sms-code-err" class="error_tip">验证码不能为空</div>
        </div>
        <div class="form_group">
            <input type="password" name="password" id="register_password" class="pass_input">
            <div class="input_tip">密码(不少于6位)</div>
            <div id="register-password-err" class="error_tip">密码不能为空</div>
        </div>
        <div class="form_group2 clearfix">
            <input type="checkbox" class="agree_input" checked>
            <p>同意使用条款，并已阅读"跟帖评论自律管理承诺书"</p>
            <div class="error_tip">请勾选</div>
        </div>
        <input type="submit" name="" value="注 册" class="input_sub">
        <div class="down_link">已有账号？<a href="javascript:;" class="to_login">立即登录</a></div>
    </div>
    <div class="mask"></div>
</form>
</body>
</html>

info/templates/news/user.html
{% extends 'news/base.html' %}

{% block titleBlock %}
    用户中心
{% endblock %}

{% block scriptBlock %}
    <script type="text/javascript" src="../../static/news/js/jquery.form.min.js"></script>
{% endblock %}


{% block categoryBlock %}

{% endblock %}

{% block contentBlock %}
    <div class="conter_con">
        <div class="user_menu_con fl">
            <div class="user_center_pic">
                <img src={% if data.user_info.avatar_url %}
                    {{ data.user_info.avatar_url }}
                {% else %}
                    "../../static/news/images/user_pic.png"
                {% endif %} alt="用户图片">
            </div>
            <div class="user_center_name">{{ data.user_info.nick_name }}</div>
            <ul class="option_list">
                <li class="active"><a href="{{ url_for('user.base_info') }}" target="main_frame">基本资料</a></li>
                <li><a href="/user/pic_info" target="main_frame">头像设置</a></li>
                <li><a href="/user/user_follow" target="main_frame">我的关注</a></li>
                <li><a href="/user/pass_info" target="main_frame">密码修改</a></li>
                <li><a href="/user/collection" target="main_frame">我的收藏</a></li>
                <li><a href="/user/news_release" target="main_frame">新闻发布</a></li>
                <li><a href="/user/news_list" target="main_frame">新闻列表</a></li>
            </ul>
        </div>

        <div class="user_con fr">
            <iframe src="/user/base_info" frameborder="0" name="main_frame"
                    class="main_frame"
                    id="main_frame"></iframe>
        </div>
    </div>
{% endblock %}

{% block rankBlock %}

{% endblock %}

{% block footerBlock %}

{% endblock %}

{% block authorBlock %}

{% endblock %}





















{##}
{##}
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>用户中心</title>#}
{#    <link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">#}
{#    <link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">#}
{#    <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>#}
{#    <script type="text/javascript" src="../../static/news/js/jquery.form.min.js"></script>#}
{#    <script type="text/javascript" src="../../static/news/js/main.js"></script>#}
{#</head>#}
{#<body>#}
{#<div class="header_con">#}
{#    <div class="header">#}
{#        <a href="#" class="logo fl"><img src="../../static/news/images/logo.png" alt="logo"></a>#}
{#        <div class="user_login fr" style="display: block;">#}
{#            <img src="../../static/news/images/user_pic.png" class="lgin_pic">#}
{#            <a href="#">用户张山</a>#}
{#            <a href="#">退出</a>#}
{#        </div>#}
{#    </div>#}
{#</div>#}
{##}
{#<div class="conter_con">#}
{#    <div class="user_menu_con fl">#}
{#        <div class="user_center_pic">#}
{#            <img src="../../static/news/images/user_pic.png" alt="用户图片">#}
{#        </div>#}
{#        <div class="user_center_name">用户张山</div>#}
{##}
{#        <ul class="option_list">#}
{#            <li class="active"><a href="../../static/news/html/user_base_info.html" target="main_frame">基本资料</a></li>#}
{#            <li><a href="../../static/news/html/user_pic_info.html" target="main_frame">头像设置</a></li>#}
{#            <li><a href="../../static/news/html/user_follow.html" target="main_frame">我的关注</a></li>#}
{#            <li><a href="../../static/news/html/user_pass_info.html" target="main_frame">密码修改</a></li>#}
{#            <li><a href="../../static/news/html/user_collection.html" target="main_frame">我的收藏</a></li>#}
{#            <li><a href="../../static/news/html/user_news_release.html" target="main_frame">新闻发布</a></li>#}
{#            <li><a href="../../static/news/html/user_news_list.html" target="main_frame">新闻列表</a></li>#}
{#        </ul>#}
{#    </div>#}
{##}
{#    <div class="user_con fr">#}
{#        <iframe src="../../static/news/html/user_base_info.html" frameborder="0" name="main_frame" class="main_frame"#}
{#                id="main_frame"></iframe>#}
{#    </div>#}
{#</div>#}
{#<div class="footer">#}
{#    <div class="footer_links">#}
{#        <a href="">关于我们</a>#}
{#        <span>|</span>#}
{#        <a href="">联系我们</a>#}
{#        <span>|</span>#}
{#        <a href="">招聘人才</a>#}
{#        <span>|</span>#}
{#        <a href="">友情链接</a>#}
{#    </div>#}
{#    <p class="copyright">#}
{#        CopyRight © 2018 新经资讯信息技术有限公司 All Rights Reserved<br/>#}
{#        电话：010-****888 京ICP备*******8号#}
{#    </p>#}
{#</div>#}
{##}
{#<!-- 登录表单 -->#}
{#<form class="login_form_con">#}
{#    <div class="login_form">#}
{#        <div class="login_title">#}
{#            <h3>登 录</h3>#}
{#            <a href="javascript:;" class="shutoff"></a>#}
{#        </div>#}
{#        <div class="form_group">#}
{#            <input type="text" name="username" autocomplete="off">#}
{#            <div class="input_tip">用户名/手机号</div>#}
{#        </div>#}
{#        <div class="form_group">#}
{#            <input type="password" name="password">#}
{#            <div class="input_tip">密码(不少于6位)</div>#}
{#        </div>#}
{#        <input type="submit" name="" value="登 录" class="input_sub">#}
{#        <div class="down_link">还没有账号？<a href="#" class="to_register">立即注册</a></div>#}
{#    </div>#}
{#    <div class="mask"></div>#}
{#</form>#}
{##}
{#<!-- 注册表单 -->#}
{#<form class="register_form_con">#}
{#    <div class="register_form">#}
{#        <div class="register_title">#}
{#            <h3>注 册</h3>#}
{#            <a href="javascript:;" class="shutoff"></a>#}
{#        </div>#}
{#        <div class="form_group">#}
{#            <input type="text" name="username" autocomplete="off" class="phone_input">#}
{#            <div class="input_tip">手机号</div>#}
{#            <div class="error_tip">手机号不能为空</div>#}
{#        </div>#}
{#        <div class="form_group">#}
{#            <input type="password" name="code_pwd" class="code_pwd">#}
{#            <div class="input_tip">手机验证码</div>#}
{#            <a href="javascript:;" class="get_code">点击获取验证码</a>#}
{#            <div class="error_tip">验证码不能为空</div>#}
{#        </div>#}
{#        <div class="form_group">#}
{#            <input type="password" name="password" class="pass_input">#}
{#            <div class="input_tip">密码(不少于6位)</div>#}
{#            <div class="error_tip">密码不能为空</div>#}
{#        </div>#}
{#        <div class="form_group">#}
{#            <input type="password" name="code_pwd" class="code_pwd">#}
{#            <div class="input_tip">图形验证码</div>#}
{#            <img src="../../static/news/images/pic_code.png" class="get_pic_code">#}
{#            <div class="error_tip">图形码不能为空</div>#}
{#        </div>#}
{##}
{#        <div class="form_group2 clearfix">#}
{#            <input type="checkbox" class="agree_input" checked>#}
{#            <p>同意使用条款，并已阅读"跟帖评论自律管理承诺书"</p>#}
{#            <div class="error_tip">请勾选</div>#}
{#        </div>#}
{#        <input type="submit" name="" value="注 册" class="input_sub">#}
{#        <div class="down_link">已有账号？<a href="#" class="to_login">立即登录</a></div>#}
{#    </div>#}
{#    <div class="mask"></div>#}
{#</form>#}
{#</body>#}
{#</html>#}

info/templates/news/user_pass_info.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>用户中心</title>
	<link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">
	<link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">
        <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="../../static/news/js/user_pass_info.js"></script>
</head>
<body class="inframe_body">
    <form class="pass_info">
        <h3>密码修改</h3>
        <div class="form-group">
            <label>当前密码：</label>
            <input type="password" name="old_password" class="input_txt">
        </div>
        <div class="form-group">
            <label>新密码：</label>
            <input type="password" name="new_password" class="input_txt">
        </div>
        <div class="form-group">
            <label>确认密码：</label>
            <input type="password" name="new_password2" class="input_txt">
        </div>
       <div class="error_tip">提示信息</div>
        <div class="form-group">
            <input type="submit" value="保 存" class="input_sub">
        </div>
    </form>
</body>
</html>